services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        image: server:master
        container_name: server
        ports:
            - "8080:8080"
        volumes:
            - .:/app:z
        env_file:
            - ./.envs/.server.env
        networks:
            - gopher-social-backend-network
        depends_on:
            postgres:
                condition: service_healthy
            mailpit:
                condition: service_healthy

    postgres:
        image: postgres:16
        container_name: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.envs/.postgres.env
        networks:
            - gopher-social-backend-network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 30s
            retries: 3
            start_period: 10s
            timeout: 10s

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        ports:
            - "5050:80"
        env_file:
            - ./.envs/.pgadmin.env
        networks:
            - gopher-social-backend-network

    mailpit:
        image: axllent/mailpit:latest
        container_name: mailpit
        volumes:
            - mailpit_data:/data
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - gopher-social-backend-network
        healthcheck:
            test: [ "CMD-SHELL", "nc -z localhost 1025" ]
            interval: 30s
            retries: 3
            start_period: 10s
            timeout: 10s

networks:
    gopher-social-backend-network:
        driver: bridge

volumes:
    postgres_data:
    mailpit_data:
